"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const ai_controller_1 = require("./ai.controller");
const auth_1 = require("../../middleware/auth");
const router = (0, express_1.Router)();
router.use(auth_1.authenticate);
router.post('/query', ai_controller_1.queryAI);
router.get('/suggestions', ai_controller_1.getSuggestions);
exports.default = router;
